### ISSUE TITLE
URLCheck fails if running via command line

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-environmentcheck#19]
if you run a URLCheck() via command line, it returns the redirect HTML, instead of a success/ failure code:

```
<p>Redirecting to <a href="*URL HERE*" title="Click this link if your browser does not redirect you"*URL HERE*... (output started on C:\xampp\htdocs\op\framework\dev\TaskRunner.php, line 67)</a></p>
```

**Comment by dhensby** [comment]
Can you replicate this on a fresh install? Perhaps you're using `Director::forceWWW()`?

This may have been fixed in 3.2.1

**Comment by torleif** [comment]
@dhensby I've tested 3.2.1, and the issue still persists. 

I think however I might be doing something wrong. Both running /dev/health and /dev/check via cli-script and framework/sake returns nothing. So I'm calling the EnvironmentCheckSuite via a custom queued job task as such:

```

		$environmentSuite = EnvironmentCheckSuite::inst('check', 'Environment status');
		$result = $environmentSuite->run();

		// create email
		$resultText = $result->customise(array(
					"URL" => Director::absoluteBaseURL(),
					"Title" => $this->title,
					"Name" => $this->checkSuiteName,
					"ErrorCode" => $this->errorCode,
				))->renderWith("EnvironmentChecker");

		if ($result->Status() == "OK") {
			echo "Everything OK!\n";
		} 
.. etc
```

Am I expected to create my own task for running this job via CLI, or is there a standard way to do it?

**Comment by dhensby** [comment]
@torleif can you expand on the context of this check a bit more and how you're running it via CLI?

**Comment by dhensby** [comment]
Ok - I just tried a fresh install and added `EnvironmentCheckSuite::register('check', 'URLCheck("")', "Is the homepage accessible?");` to my `mysite/_config.php`

When I run:

```sh
$ framework/sake dev/check
```

If get HTML output (yuck) but ultimately it says:

```html
...
<tr><td>Is the homepage accessible?</td> <td class="OK">OK</td> <td>Success retrieving &quot;&quot;</td></tr>
...
```

**Comment by torleif** [comment]
There's defiantly something going on on my end, as **framework/sake dev/check** returns nothing on OSX, windows and Linux. Hence why I put the EnvironmentCheckSuite in a queued job

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
